
GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "Hassan",
  "password": "13s3C",
  "mainAddress": {
    "street": "DenverStr. 96",
    "zip": 36048,
    "city": "Berlin",
    "country": "Germany"
  }
}



###

//GET http://localhost:3000/api/users/123 - throws error due to fake id

GET http://localhost:3000/api/users/683eb39f58473396c26db6fc


###
DELETE  http://localhost:3000/api/users/68400b9ea9e49c9794b28d62 

###
DELETE  http://localhost:3000/api/users/  
