GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
   "userName": "Hypierion",
   "password": "1234n"
}

###

//GET http://localhost:3000/api/users/123 - throws error due to fake id


GET http://localhost:3000/api/users/683eb39f58473396c26db6fc